# exceptions.py

class AuthCanceled(Exception):
    pass
